export const UNAUTHORIZED = 0

export const SIGN_UP = {
  SUCCESS: 1001,
  DUPLICATED_ID: 1011,
  DIFFERENT_PASSWORDS: 1012,
  INVALID_PASSWORD: 1013,
} as const

export const SIGN_IN = {
  SUCCESS: 1101,
  NONEXISTENT_ID: 1111,
  INVALID_PASSWORD: 1112,
} as const

export const ROLLING_PAPER = {
  INVITATION_CODE: {
    CREATION_SUCCESS: 3101,
    QUERY_SUCCESS: 3001,
    QUERY_FAILURE: 3011,
  },
  INVITATION_OR_RECEIPT_CODE: {
    SUCCESS: 3005,
    INVALID_SHARING_CODE: 3111,
  },
  INVITATION_SUCCESS_STATUS: "E",
  RECEIPT_SUCCESS_STATUS: "V",
  CREATION: {
    SUCCESS: 3002,
    FAILURE: 3012,
    DUPLICATED_SHARING_CODE: 3102,
  },
} as const

export const ACCOUNT_INQUIRY = {
  SUCCESS: 1303,
  FAILURE: 1311,
}
