export type TColor =
  | "danger"
  | "fill-danger"
  | "warning"
  | "fill-warning"
  | "normal"
  | "fill-normal"
  | "info"
  | "fill-info"
  | "light-4"
  | "fill-light-4"
  | "light-3"
  | "fill-light-3"
  | "light-2"
  | "fill-light-2"
  | "light-1"
  | "fill-light-1"
  | "default"
  | "fill-default"
  | "dark-1"
  | "fill-dark-1"
  | "dark-2"
  | "fill-dark-2"
  | "dark-3"
  | "fill-dark-3"
  | "dark-4"
  | "fill-dark-4"

export type TIconSize = "xs" | "sm" | "md" | "lg" | "xl"
